version: '3.8'

services:
  webapi:
    image: password-webapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ENCRYPTION_IV=${ENCRYPTION_IV}
      - jwt_key=${JWT_KEY}
      - POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
    ports:
      - "80:80"
      - "403:403"