name: Build. Test. Deploy.

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.403"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test
  build-image-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: azure_deployment
    env:
      ACR_NAME: ${{ vars.ACR_NAME }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      APP_SERVICE_NAME: ${{ vars.APP_SERVICE_NAME }}
      APP_RESOURCE_GROUP: ${{ vars.APP_RESOURCE_GROUP }}
      APP_NAME: ${{ vars.APP_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{env.ACR_NAME}}.azurecr.io/${{env.IMAGE_NAME}}:${{ github.sha }} .
          docker push ${{env.ACR_NAME}}.azurecr.io/${{env.IMAGE_NAME}}:${{ github.sha }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.APP_NAME}}
          slot-name: production
          images: ${{env.ACR_NAME}}.azurecr.io/${{env.IMAGE_NAME}}:${{ github.sha }}

      - name: Update Azure App Service to use latest image
        run: |
          az webapp config container set --name ${{env.APP_NAME}} \
            --resource-group ${{env.APP_RESOURCE_GROUP}} \
            --docker-custom-image-name ${{env.ACR_NAME}}.azurecr.io/${{env.IMAGE_NAME}}:${{ github.sha }}

      - name: Restart Azure App Service
        run: |
          az webapp restart --name ${{env.APP_NAME}} --resource-group ${{env.APP_RESOURCE_GROUP}}
